services:
  couchdb:
    image: couchdb:3.3
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin123
    ports:
      - "5984:5984"

  gateway:
    build:
      context: ..
      dockerfile: docker/gateway.Dockerfile
    environment:
      FABRIC_MOCK: "true"
      PORT: "3001"
      DB_TYPE: "couchdb"
      COUCHDB_URL: "http://admin:admin123@couchdb:5984"
    ports:
      - "3002:3001"
    depends_on:
      - couchdb

  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    environment:
      GATEWAY_URL: http://gateway:3001
      CORS_ORIGINS: http://localhost:5173,http://localhost:5174,http://127.0.0.1:5173,http://127.0.0.1:5174
    ports:
      - "8000:8000"
    depends_on:
      - gateway

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    environment:
      VITE_API_URL: http://localhost:8000
    ports:
      - "5174:5173"
    depends_on:
      - backend
