services:
  gateway:
    environment:
      FABRIC_MOCK: "false"
      FABRIC_MSP_ID: Org1MSP
      FABRIC_CHANNEL: mychannel
      FABRIC_CHAINCODE: consentcc
      FABRIC_PEER_ENDPOINT: host.docker.internal:7051
      FABRIC_PEER_HOST_ALIAS: peer0.org1.example.com
      FABRIC_CERT_PATH: /fabric/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem
      FABRIC_KEY_PATH: /fabric/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk
      FABRIC_TLS_CERT_PATH: /fabric/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
    volumes:
      - ../blockchain/test-network:/fabric:ro
